apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yarden-ziv/argocd-lab
    targetRevision: main
    path: apps/whoami/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
